name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fizzbuzz_test
      id: fizzbuzz_test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: fizzbuzz_test
        setup-command: ''
        command: node main.js
        input: ''
        expected-output: |-
          1
          2
          Fizz
          4
          Buzz
          Fizz
          7
          8
          Fizz
          Buzz
          11
          Fizz
          13
          14
          FizzBuzz
          16
          17
          Fizz
          19
          Buzz
          Fizz
          22
          23
          Fizz
          Buzz
          26
          Fizz
          28
          29
          FizzBuzz
          31
          32
          Fizz
          34
          Buzz
          Fizz
          37
          38
          Fizz
          Buzz
          41
          Fizz
          43
          44
          FizzBuzz
          46
          47
          Fizz
          49
          Buzz
          Fizz
          52
          53
          Fizz
          Buzz
          56
          Fizz
          58
          59
          FizzBuzz
          61
          62
          Fizz
          64
          Buzz
          Fizz
          67
          68
          Fizz
          Buzz
          71
          Fizz
          73
          74
          FizzBuzz
          76
          77
          Fizz
          79
          Buzz
          Fizz
          82
          83
          Fizz
          Buzz
          86
          Fizz
          88
          89
          FizzBuzz
          91
          92
          Fizz
          94
          Buzz
          Fizz
          97
          98
          Fizz
          Buzz
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: run
      id: run
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: run
        setup-command: ''
        command: node main.js
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIZZBUZZ_TEST_RESULTS: "${{steps.fizzbuzz_test.outputs.result}}"
        RUN_RESULTS: "${{steps.run.outputs.result}}"
      with:
        runners: fizzbuzz_test,run
